// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHsz7FucO6h-j9xjuZz237NOJn9HMNXp8',
    appId: '1:488658598124:web:d56232db423e8bfe080dc9',
    messagingSenderId: '488658598124',
    projectId: 'home-food-d2d08',
    authDomain: 'home-food-d2d08.firebaseapp.com',
    storageBucket: 'home-food-d2d08.appspot.com',
    measurementId: 'G-ESM930D07G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHQtMeiUz4jfrfXIc5CTeGKiy4IxtkmYg',
    appId: '1:488658598124:android:bd3838398d67058e080dc9',
    messagingSenderId: '488658598124',
    projectId: 'home-food-d2d08',
    storageBucket: 'home-food-d2d08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAykGiKLYUz3M6c6lYuGFM08-9z6r54oXk',
    appId: '1:488658598124:ios:1885d239bd5faa6d080dc9',
    messagingSenderId: '488658598124',
    projectId: 'home-food-d2d08',
    storageBucket: 'home-food-d2d08.appspot.com',
    iosBundleId: 'com.example.homeFoodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAykGiKLYUz3M6c6lYuGFM08-9z6r54oXk',
    appId: '1:488658598124:ios:1885d239bd5faa6d080dc9',
    messagingSenderId: '488658598124',
    projectId: 'home-food-d2d08',
    storageBucket: 'home-food-d2d08.appspot.com',
    iosBundleId: 'com.example.homeFoodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHsz7FucO6h-j9xjuZz237NOJn9HMNXp8',
    appId: '1:488658598124:web:242eb5ce4528b6b0080dc9',
    messagingSenderId: '488658598124',
    projectId: 'home-food-d2d08',
    authDomain: 'home-food-d2d08.firebaseapp.com',
    storageBucket: 'home-food-d2d08.appspot.com',
    measurementId: 'G-WL63HTYPEL',
  );
}
