
import 'package:get/get.dart';

class MyTranslation extends Translations {

  @override
  Map<String, Map<String, String>> get keys => {
    "ar": {
      "choose": "اختار اللغه",
      "Ar": "لغة عربية",
      "callus": "تحدث معانا",
      "notice": "إشعار",
      "del": "تم حذف المنتج من المفضلة",
      "add": "تم أضافة المنتج الى المفضلة",
      "not": "تعطيل الاشعارات",
      "error": "خطأ",
      "En": "اللغة الانجليزية",
      "signin": "تسجيل الدخول",
      "OrContinueWith": "أو الاستمرار مع",
      "CreateAccount": "انشاء حساب",
      "welcome": "مرحبا بكم فى Known Tech !",
      "par":
      "سجل دخولك عبر البريد الالكترونى و كلمة المرور او عبر وسائل التواصل الاجتماعى",
      "email": "الايميل",
      "hintemail": "ادخل البريد الالكترونى",
      "password": "كلمة السر",
      "hintpass": "ادخل كلمة السر",
      "forget": "نسيت كلمة السر ؟",
      "have": "ليس لديك حساب ؟  ",
      "signup": " انشاء حساب  ",
      "youhave": "هل لديك حساب بالفعل ؟  ",
      "username": "اسم المستخدم",
      "hintusername": "ادخل اسم المستخدم",
      "phone": "الهاتف",
      "hintphone": "ادخل رقم الهاتف",
      "continue": "متابعة",
      "check": "التحقق من البريد الالكترونى",
      "verification": "رمز التحقق",
      "checkcode": "تحقق من الكود",
      "parcheckcode":
      "الرجاء إدخال عنوان بريدك الإلكتروني للحصول على رمز التحقق",
      "parcheckcode2": "الرجاء إدخال رمز الرقم المرسل إلى  ",
      "reset": "إعادة تعيين كلمة المرور",
      "newpass": "لمة مرور جديدة",
      "newpass2": "من فضلك ادخل كلمة مرور جديدة",
      "save": "حفظ",
      "repassword": "تاكيد كلمة المرور",
      "rehintpass": "ادخل كلمة المرور مره اخرى للتاكيد",
      "successsignup": "نجح انشاء الحساب",
      "successresetpass": "نحج تعين كلمة مرور جديدة ",
      "gotologin": "اذهب الى صفحة تسجيل الدخول",
      "titleexit": "تنبية",
      "bodyexit": "هل تريد الخروج من التطبيق ؟",
      "yes": "موافق",
      "no": "الغاء",
      "setting": "الاعدادت",
      "language": "اللغه",
      "about": "من نحن",
      "country": "الدولة",
      "help": "مساعده",
      "logout": "تسجيل الخروج",
    },
    "en": {
      "choose": "Choose Language",
      "Ar": "Arabic",
      "En": "English",
      "callus": "Talk To Us",
      "notice": "Notice",
      "not": "Disable Notifications",
      "addaddress": "Add New Address",
      "discount": "Discount",
      "apply": "Apply Discount",
      "error": "Error",
      "signin": "Log in",
      "OrContinueWith": "Or Continue With",
      "anotherAccount": "Sing in with another account",
      "CreateAccount": " Create Account",
      "welcome": "Welcome to Known Tech !",
      "par":
      "Sign In With Email And Password OR Continue With Social Media",
      "email": "Email",
      "hintemail": "Enter Your Email",
      "password": "Password",
      "hintpass": "Enter Your Password",
      "forget": "Forget Password ?",
      "have": "Don't have an account ?  ",
      "signup": " Sign Up ",
      "youhave": "Do you already have an account ?  ",
      "username": "User Name",
      "hintusername": "Enter Your Name",
      "phone": "Phone",
      "hintphone": "Enter Your Phone Number",
      "continue": "Continue",
      "check": "Check Your Email",
      "verification": "Verification Code",
      "checkcode": "Check Code",
      "parcheckcode":
      "Please Enter Your Email Address To Receive A Verification Code",
      "parcheckcode2": "Please Enter The Digit Code Sent To ",
      "reset": "Reset Password",
      "newpass": "New Password",
      "newpass2": "Please Enter New Password",
      "save": "Save",
      "repassword": "Re Password",
      "rehintpass": "Re Enter Your Password",
      "successsignup": "Success SignUp",
      "successresetpass": "Success Reset Password",
      "congratulations": "Congratulations",
      "gotologin": "Go To Login",
      "titleexit": "Alert",
      "bodyexit": "Do you want to exit the application?",
      "yes": "Confirm",
      "no": "Cancel",
      "note": "Add Details and Notes",
      "res": "Number of Reception pieces",
      "findproduct": "Find Product",
      "orders": "Orders",
      "price": "price",
      "country": "Country",
      "setting": "Setting",
      "balconies": "Number of Balconies",
      "language": "Language",
      "about": "About Us",
      "help": "Help",
      "delete": "Success Delete",
      "logout": "Log Out",
      "click": "Click Here",
      "address": "Address",
      "addresshint": "Street - building - floor number - apartment",
      "soon": "Soon !",
      "requesttime": "Request time : ",
    },
  };
}
